# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created

name: Node.js Package

on:
  release:
    types: [ created ]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Use Node.js in LTS
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm test --if-present

  publish-npm:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Use Node.js in LTS
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false # never use caching in release builds
      - name: Install dependencies
        run: npm ci
      - name: Publish to registry
        run: npm publish
